import type {
  User,
  PermissionGroup,
  AuditLog,
  Notification,
  Product,
  Customer,
  Ticket,
  Transaction,
  SystemSettings,
} from "./types"

// Default users
export const defaultUsers: User[] = [
  {
    id: 1,
    name: "Primary Admin",
    email: "primary@example.com",
    role: "admin",
    status: "active",
    verified: true,
    isPrimaryAdmin: true,
    passwordChanged: true,
    lastLogin: new Date().toISOString(),
    permissions: [
      "manage_users",
      "manage_inventory",
      "manage_sales",
      "manage_customers",
      "manage_tickets",
      "view_reports",
      "manage_settings",
      "process_refunds",
      "view_audit_logs",
      "manage_backups",
    ],
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    name: "Admin User",
    email: "admin@example.com",
    role: "admin",
    status: "active",
    verified: true,
    isPrimaryAdmin: false,
    passwordChanged: false,
    lastLogin: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    permissions: ["manage_inventory", "manage_sales", "manage_customers", "manage_tickets", "view_reports"],
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    name: "Staff User",
    email: "staff@example.com",
    role: "staff",
    status: "active",
    verified: true,
    passwordChanged: false,
    lastLogin: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    permissions: ["manage_sales", "manage_customers"],
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    name: "John Smith",
    email: "john.smith@example.com",
    role: "staff",
    status: "inactive",
    verified: false,
    passwordChanged: false,
    lastLogin: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    permissions: ["manage_sales"],
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    role: "staff",
    status: "active",
    verified: false,
    passwordChanged: false,
    lastLogin: "-",
    permissions: ["manage_sales"],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Permission groups
export const permissionGroups: PermissionGroup[] = [
  {
    name: "User Management",
    permissions: ["manage_users"],
  },
  {
    name: "Inventory",
    permissions: ["manage_inventory"],
  },
  {
    name: "Sales",
    permissions: ["manage_sales", "process_refunds"],
  },
  {
    name: "Customers",
    permissions: ["manage_customers"],
  },
  {
    name: "Tickets",
    permissions: ["manage_tickets"],
  },
  {
    name: "Reports",
    permissions: ["view_reports"],
  },
  {
    name: "Settings",
    permissions: ["manage_settings"],
  },
  {
    name: "Security",
    permissions: ["view_audit_logs", "manage_backups"],
  },
]

// Sample audit logs
export const sampleAuditLogs: AuditLog[] = [
  {
    id: 1,
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "Product Created",
    details: "Added new product: Product 7",
    ip: "192.168.1.1",
    module: "Inventory",
  },
  {
    id: 2,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "User Updated",
    details: "Modified user permissions for Staff User",
    ip: "192.168.1.1",
    module: "User Management",
  },
  {
    id: 3,
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "Settings Changed",
    details: "Updated tax rate from 7% to 7.5%",
    ip: "192.168.1.1",
    module: "Settings",
  },
  {
    id: 4,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "User Created",
    details: "Added new user: John Smith",
    ip: "192.168.1.1",
    module: "User Management",
  },
  {
    id: 5,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 2 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "Product Updated",
    details: "Modified price for Product 3 from $39.99 to $42.99",
    ip: "192.168.1.1",
    module: "Inventory",
  },
  {
    id: 6,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "Backup Created",
    details: "Manual system backup initiated",
    ip: "192.168.1.1",
    module: "System",
  },
  {
    id: 7,
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 - 5 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "User Deleted",
    details: "Removed user: Jane Wilson",
    ip: "192.168.1.1",
    module: "User Management",
  },
  {
    id: 8,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "Report Generated",
    details: "Created sales report for Q1 2023",
    ip: "192.168.1.1",
    module: "Reports",
  },
  {
    id: 9,
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000 - 7 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "Ticket Closed",
    details: "Resolved ticket TKT-002: Product Exchange",
    ip: "192.168.1.1",
    module: "Tickets",
  },
  {
    id: 10,
    timestamp: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    user: "Admin User",
    action: "System Update",
    details: "Installed system update v2.0.5",
    ip: "192.168.1.1",
    module: "System",
  },
]

// Sample notifications
export const sampleNotifications: Notification[] = [
  {
    id: 1,
    title: "Low Stock Alert",
    message: "Product 5 is running low on stock (3 remaining)",
    type: "warning",
    read: false,
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    link: "/inventory",
  },
  {
    id: 2,
    title: "New User Registration",
    message: "Sarah Johnson has registered and is awaiting verification",
    type: "info",
    read: false,
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    link: "/admin/users",
  },
  {
    id: 3,
    title: "System Update Available",
    message: "Version 2.1.0 is available for installation",
    type: "info",
    read: true,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    link: "/settings/advanced",
  },
  {
    id: 4,
    title: "Backup Completed",
    message: "Daily system backup completed successfully",
    type: "success",
    read: true,
    timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000 - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    title: "Failed Login Attempt",
    message: "Multiple failed login attempts detected from IP 203.0.113.1",
    type: "error",
    read: false,
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    link: "/admin/logs",
  },
]

// Sample products
export const sampleProducts: Product[] = [
  {
    id: 1,
    name: "Product 1",
    sku: "SKU001",
    category: "Category A",
    price: 19.99,
    cost: 10.0,
    stock: 45,
    reorderLevel: 10,
    image: "/placeholder.svg?height=80&width=80",
  },
  {
    id: 2,
    name: "Product 2",
    sku: "SKU002",
    category: "Category A",
    price: 29.99,
    cost: 15.0,
    stock: 32,
    reorderLevel: 8,
    image: "/placeholder.svg?height=80&width=80",
  },
  {
    id: 3,
    name: "Product 3",
    sku: "SKU003",
    category: "Category B",
    price: 39.99,
    cost: 20.0,
    stock: 18,
    reorderLevel: 5,
    image: "/placeholder.svg?height=80&width=80",
  },
  {
    id: 4,
    name: "Product 4",
    sku: "SKU004",
    category: "Category B",
    price: 49.99,
    cost: 25.0,
    stock: 7,
    reorderLevel: 10,
    image: "/placeholder.svg?height=80&width=80",
  },
  {
    id: 5,
    name: "Product 5",
    sku: "SKU005",
    category: "Category C",
    price: 59.99,
    cost: 30.0,
    stock: 3,
    reorderLevel: 5,
    image: "/placeholder.svg?height=80&width=80",
  },
  {
    id: 6,
    name: "Product 6",
    sku: "SKU006",
    category: "Category C",
    price: 69.99,
    cost: 35.0,
    stock: 12,
    reorderLevel: 5,
    image: "/placeholder.svg?height=80&width=80",
  },
]

// Sample customers
export const sampleCustomers: Customer[] = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@example.com",
    phone: "(555) 123-4567",
    totalSpent: 1245.67,
    lastPurchase: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 2,
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "(555) 987-6543",
    totalSpent: 876.54,
    lastPurchase: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 3,
    name: "Robert Johnson",
    email: "robert.johnson@example.com",
    phone: "(555) 456-7890",
    totalSpent: 2345.67,
    lastPurchase: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 4,
    name: "Emily Wilson",
    email: "emily.wilson@example.com",
    phone: "(555) 234-5678",
    totalSpent: 543.21,
    lastPurchase: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 5,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    phone: "(555) 876-5432",
    totalSpent: 1987.65,
    lastPurchase: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Sample tickets
export const sampleTickets: Ticket[] = [
  {
    id: "TKT-001",
    customer: "John Smith",
    subject: "Refund Request",
    status: "Open",
    priority: "High",
    created: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "TKT-002",
    customer: "Jane Doe",
    subject: "Product Exchange",
    status: "In Progress",
    priority: "Medium",
    created: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "TKT-003",
    customer: "Robert Johnson",
    subject: "Missing Item",
    status: "Open",
    priority: "High",
    created: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    lastUpdated: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Sample transactions
export const sampleTransactions: Transaction[] = [
  {
    id: "TRX-1001",
    customer: "John Smith",
    date: new Date().toISOString(),
    amount: 129.99,
    status: "Completed",
    paymentMethod: "Credit Card",
  },
  {
    id: "TRX-1002",
    customer: "Jane Doe",
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 79.95,
    status: "Completed",
    paymentMethod: "Cash",
  },
  {
    id: "TRX-1003",
    customer: "Robert Johnson",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 249.5,
    status: "Completed",
    paymentMethod: "Credit Card",
  },
  {
    id: "TRX-1004",
    customer: "Emily Wilson",
    date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 59.99,
    status: "Completed",
    paymentMethod: "Cash",
  },
  {
    id: "TRX-1005",
    customer: "Michael Brown",
    date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    amount: 349.95,
    status: "Completed",
    paymentMethod: "Credit Card",
  },
]

// Default system settings
export const defaultSystemSettings: SystemSettings = {
  general: {
    language: "en",
    timezone: "africa-johannesburg",
    currency: "zar",
    dateFormat: "dd-mm-yyyy",
    receiptFooter: "Thank you for your business! Returns accepted within 14 days with receipt.",
    receiptPrinter: "thermal-printer",
    autoPrint: true,
  },
  company: {
    name: "SA POS System",
    vatNumber: "4123456789",
    email: "info@sapos.com",
    phone: "+27 21 123 4567",
    address: "123 Main Street, Cape Town, 8001, South Africa",
    website: "https://www.sapos.com",
  },
  security: {
    twoFactorAuth: false,
    sessionTimeout: true,
    timeoutDuration: 30,
  },
  billing: {
    taxRate: 15,
    taxCalculation: "inclusive",
    taxNumberLabel: "VAT #",
    showTaxBreakdown: true,
    acceptCreditCards: true,
    acceptCash: true,
    acceptInvoices: true,
  },
  notifications: {
    emailLowStock: true,
    emailDailySummary: true,
    emailNewUsers: true,
    systemUpdates: true,
    securityAlerts: true,
  },
  appearance: {
    themeMode: "light",
    primaryColor: "#0f172a",
    accentColor: "#2563eb",
    compactMode: false,
    largeText: false,
  },
  advanced: {
    backupFrequency: "daily",
    backupRetention: 30,
  },
}
